openapi: 3.0.0
info:
  title: JustIceQAQ API Docs
  description: 提供 JustIceQAQ 自己整理的 API (可能會過時)
  version: 1.0.0
servers:
  - url: https://justiceqaq.github.io/api/data
paths:
  /taiwan-zip-code.json:
    get:
      summary: 查詢台灣郵遞區號
      responses:
        '200':
          description: 成功回應
          content:
            application/json:
              schema:
                type: object
                properties:
                  cities:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 臺北市
                        code:
                          type: integer
                          example: 100
                        regions:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: 中山區
                              code:
                                type: integer
                                example: 104
              example:
                cities:
                  - name: "臺北市"
                    code: 100
                    regions:
                      - name: "中山區"
                        code: 104
                      - name: "大安區"
                        code: 106
  /taiwan-identity-card-fmt.json:
    get:
      summary: 查詢台灣身分證代號
      responses:
        '200':
          description: 成功回應
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: A
                        value:
                          type: string
                          example: "10"
                        city:
                          type: string
                          example: 臺北市
                  disable:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: L
                        value:
                          type: string
                          example: "20"
                        original_city:
                          type: string
                          example: 臺中縣
                        disable_datetime:
                          type: string
                          example: "2010-12-25"
                        city:
                          type: string
                          example: 臺中市
                  gender:
                    type: object
                    properties:
                      "1":
                        type: string
                        example: 男
                      "2":
                        type: string
                        example: 女
              example:
                enabled:
                  - code: "A"
                    value: "10"
                    city: "臺北市"
                disable:
                  - code: "L"
                    value: "20"
                    original_city: "臺中縣"
                    disable_datetime: "2010-12-25"
                    city: "臺中市"
                gender:
                  "1": "男"
                  "2": "女"
  /taiwan-city-fmt.json:
    get:
      summary: 查詢台灣縣市資料
      responses:
        '200':
          description: 成功回應
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: 彰化縣
                    level:
                      type: string
                      example: 縣
                    english_name:
                      type: string
                      example: Changhua County
                    code:
                      type: object
                      properties:
                        official:
                          type: string
                          example: "10007"
                        iso_3166:
                          type: string
                          example: TW-CHA
                    image:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 25px-Flag_of_Changhua_County.svg.png
                        extension:
                          type: string
                          example: .png
                        base64:
                          type: string
                          example: data:image/png;base64,iVBORw0KGgoAAAANSUh...
              example:
                - name: "彰化縣"
                  level: "縣"
                  english_name: "Changhua County"
                  code:
                    official: "10007"
                    iso_3166: "TW-CHA"
                  image:
                    name: "25px-Flag_of_Changhua_County.svg.png"
                    extension: ".png"
                    base64: "data:image/png;base64,iVBORw0KGgoAAAANSUh..."


